apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-state-metrics-config

labels:
  - pairs:
      app: kube-state-metrics
      managedBy: argocd
      managementCodeGroup: chrismlee42-dev
      managementCodeProject: kube-state-metrics-config

namespace: kube-system

resources:
  # Determine latest stable version from https://github.com/kubernetes/kube-state-metrics/tags
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/tags/v2.17.0/examples/standard/cluster-role-binding.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/tags/v2.17.0/examples/standard/cluster-role.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/tags/v2.17.0/examples/standard/deployment.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/tags/v2.17.0/examples/standard/service-account.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/tags/v2.17.0/examples/standard/service.yaml
